<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'tevtev');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'YAgXkFG1xnkTO8voXHJq4COT5RDrxL056CYX2FC9r2TK4eSsFJ40Xy6A');
define('_COOKIE_IV_', 'xDWSJCrf');
define('_PS_CREATION_DATE_', '2014-12-27');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'as3n7yKtATNcYgPZpoj1EIgFq8v3n563');
define('_RIJNDAEL_IV_', 'jkZNbsxTqMhAY47Vw9DJQg==');
